### ISSUE TITLE
404 due to multiple version new feature

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/website#108]
### Problem

At least one URL in documentation link to 404 due to the new feature of versionning.
/docs/current/ was fine before but isn't anymore.

#### Missing page
https://api-platform.com/docs/current/core/extensions/ 
from 
https://api-platform.com/docs/core/filters/#creating-custom-filters 
When you click on "Extensions"

This case may be at other places, /current/ should be replace with /

**Comment by alanpoulain** [comment]
Fixed by https://github.com/api-platform/website/pull/109.
