### ISSUE TITLE
Algolia search return duplicated results

### ISSUE THREAD

**Issue by comxd** [api-platform/website#110]
![image](https://user-images.githubusercontent.com/9022239/57926098-af293e80-78aa-11e9-8500-39adab33e26f.png)

One solution can be to display the doc item version to the search results box or simply ignore duplicated results?

![image](https://user-images.githubusercontent.com/9022239/57926945-fca6ab00-78ac-11e9-836b-6da79d98943d.png)

**Comment by dunglas** [comment]
Thanks for reporting, it has been fixed.
