### ISSUE TITLE
Change the meta tags according to the current page

### ISSUE THREAD

**Issue by dunglas** [api-platform/website#152]
Currently, the content of meta tags (OpenGraph, description...) is hardcoded. It would better for SEO and SMO to change them according to the current page.

The lines too change are here: https://github.com/api-platform/website/blob/master/src/templates/doc.js#L14

**Comment by lex111** [comment]
Can I have more details to implement this?

**Comment by dunglas** [comment]
The OpenGraph and the meta description should use the title of the Markdown document (already used in the `<title>` element).

**Comment by sumitkharche** [comment]
@dunglas It means that we need to add 'description' tag into meta and bind pageContext.title to it. Right?
