### ISSUE TITLE
Rework markup SC player

### ISSUE THREAD

**Issue by lex111** [api-platform/website#161]
- At the moment, the SC image is not displayed, if there is no caption - this is a bug (due to `gatsby-remark-images` plugin).

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/4408379/66063474-1a1e9d80-e54c-11e9-9a7c-4f9d5cdb5c25.png)

Page - https://api-platform.com/docs/master/distribution/

</details>

- When you hover over an caption with an SC image, background of the entire clickable area is highlighted, it seems to me that it is wrong and ugly, the hover effect should be applied **only** to the caption.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/4408379/66063744-b21c8700-e54c-11e9-9e18-1270d2f5b978.png)

Page - https://api-platform.com/docs/deployment/

Should be like this:

![image](https://user-images.githubusercontent.com/4408379/66063943-18090e80-e54d-11e9-9b20-906a078d1f5e.png)

</details>

What do you think, @dunglas?

**Comment by dunglas** [comment]
Indeed it's a bug, we should do that!

**Comment by lex111** [comment]
You mind if I handle this two bugs, okay?

**Comment by dunglas** [comment]
You're very welcome!

**Comment by lex111** [comment]
I suggest making the markup more semantic, that is, like this

```html
<figure class="symfonycasts"><a href="#"><img src="#" alt="#"><figcaption>Optional caption</figcaption></a></figure>
```

It's good for you?

**Comment by dunglas** [comment]
Yes it's even better!

**Comment by lex111** [comment]
Hmm, I just thought that we can simplify the insertion SC block a bit, I mean use something like shortcode.
For example, `symfonycasts:alt="JWT screencast" link="https://symfonycasts.com/tracks/rest?cid=apip#api-platform"` transforms to HTML!

```html
<p class="symfonycasts"><a href="https://symfonycasts.com/tracks/rest?cid=apip#api-platform" class="symfonycasts"><img src="../distribution/images/symfonycasts-player.png" alt="JWT screencast"></a></span></p>
```

How does that sound?

**Comment by dunglas** [comment]
Will it work when browsing the doc files directly in GitHub? Also, Everywhere else we have a caption at the bottom of the player.

**Comment by lex111** [comment]
> Will it work when browsing the doc files directly in GitHub?

Um, nope, but is that really important? I mean, who reads the documentation on GitHub? I think you can give that up.

> Also, Everywhere else we have a caption at the bottom of the player.

Of course, caption can be provided, this is a concept, I did not just specify it.

**Comment by dunglas** [comment]
Many people read the docs directly from GH, or from their IDE. I think we should stick to standard markdown

**Comment by lex111** [comment]
Hmm, really a pity, all the more it is a valid inline code and by its contents you can understand what it represents. And we could significantly simplify the insertion of SC block, but for some reason we manually duplicate the code each time...

Nevertheless, it is strange that in reality many people read the docs on GH, it’s at least inconvenient, and it’s faster to open a website with documentation. So this is a moot point, as for me.

Well, those who look at the docs from their IDE are just the developers who do this only to edit the docs, especially considering the separate docs repository.
