### ISSUE TITLE
Align text list item

### ISSUE THREAD

**Issue by lex111** [api-platform/website#165]
| Before (right now)   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/66136199-c1124080-e603-11e9-9e4b-1ae0729312c6.png) | ![image](https://user-images.githubusercontent.com/4408379/66136251-d38c7a00-e603-11e9-9a0e-a755c557ee54.png) |

This will also fix such a bug! (page - https://api-platform.com/docs/v2.2/client-generator/troubleshooting/)

![image](https://user-images.githubusercontent.com/4408379/66136381-0c2c5380-e604-11e9-9598-534466d27da2.png)

Are we doing this or not, @dunglas?

**Comment by dunglas** [comment]
yeah, awesome, thanks for all these improvements!
