### ISSUE TITLE
Improve accessibility 

### ISSUE THREAD

**Issue by justinezahiri** [api-platform/website#175]
According to W3 ARIA, followings issues should be considered: 

- [x] Burger button does not have an accessible name.
- [x] Links to Twitter and Github in menu don't have discernable names.

- [x] In the burger button `div` is not allowed as child of `button` in this context 

- [x] `<html>` element does not have a `[lang]` attribute.

- [x] `frameborder` attribute for `iframe` tag is obsolete, use CSS instead.
- [x] `scrolling` attribute for `iframe` tag is obsolete, use CSS instead. 

- [x] Stray start tag `script`.

**Comment by justinezahiri** [comment]
I'm on it for today ;)

**Comment by Lawrence4code** [comment]
I'd like to work in it, please.
