### ISSUE TITLE
Community showcase

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/website#2]
Do you want to showcase more projects? Could we have our logo added here?

https://github.com/api-platform/website/blob/5c900e33292a2552019942515a4de81b2ac675a4/app/views/main.html#L258

**Comment by dunglas** [comment]
Yes of course. Can you open a PR?

**Comment by dunglas** [comment]
@teohhanhui What is your project name? Can you post its logo here?

**Comment by teohhanhui** [comment]
@leesiongchan

**Comment by leesiongchan** [comment]
Site url: https://tripviss.com
Logo url: https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xft1/v/t1.0-9/12002901_1648155682120681_2428956200264847149_n.png?oh=72ce8577e043e00e4aa14cb6d9eaaa54&oe=574D70B9&__gda__=1465557976_0a1147bf3b29e3115e93f1f9bd6606ef

**Comment by Simperfit** [comment]
added some time ago :p @teohhanhui @leesiongchan

**Comment by dunglas** [comment]
Closing (updated website)
