### ISSUE TITLE
Patch files should be highlighted

### ISSUE THREAD

**Issue by dunglas** [api-platform/website#221]
The`patch` format is supported by GitHub in Markdown documents but not on our website.
It looks like Prism (used by Gatsby) doesn't support it. We should add support for `patch` in Prism.

**Comment by soyuka** [comment]
you mean the `diff` format and the plugin is here: https://prismjs.com/plugins/diff-highlight/

**Comment by dunglas** [comment]
Actually it looks related to our Prism theme because the HTML markup is already correctly generated.
