### ISSUE TITLE
Image is not loaded on api-platform.com

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/website#50]
@borNfreee:
> Image about serializer (on the very beginning of the article) is not loaded on https://api-platform.com/docs/core/serialization/#the-serialization-context-groups-and-relations while it works in https://github.com/api-platform/docs/blob/2.3/core/serialization.md

(Moved from https://github.com/api-platform/docs/issues/538)

**Comment by borNfreee** [comment]
please reopen, fix was reverted

**Comment by dunglas** [comment]
Any help welcome on this one. The problem with the fix was that images weren't displayed on GitHub anymore.

**Comment by Fabious** [comment]
It's fixed 👍
