### ISSUE TITLE
Mobile version: hamburger menu should retract when scrolling

### ISSUE THREAD

**Issue by Simperfit** [api-platform/website#6]
Reported by @CecileAmrl 

<img width="394" alt="capture d ecran 2016-10-25 a 13 59 15" src="https://cloud.githubusercontent.com/assets/8024246/19685179/79aa83b0-9abb-11e6-889e-e25b02ef94af.png">

(ios 10.0.1)

**Comment by dunglas** [comment]
Closing (updated website)
