### ISSUE TITLE
Add a "contributors" page

### ISSUE THREAD

**Issue by dunglas** [api-platform/website#60]
This page new page will display the list of all API Platform contributors.

* It must display the name of the contributor, it's GitHub avatar, and have a link to his GitHub account
* Contributors must be ordered by number of contributions
* The name of repositories the user contributed to must be displayed below his name (ex : core, docs, api-doc-parser).

It should extract the list of contributors using the GitHub API or by cloning the Git repositories directly. The process must be 100% automated.

Possible implementation:

* Use the GitHub API to list all the repositories under the api-platform org
* Clone all those repositories
* Extract the list of contributors and their number of commits using Git
* Group by email

**Comment by LionelBergen** [comment]
Is this still available? Where should the contributors section or page be?

**Comment by dunglas** [comment]
It's still available! Iit should be a new page, with a link in the footer maybe.
