### ISSUE TITLE
Remove /index from prev and next links

### ISSUE THREAD

**Issue by dunglas** [api-platform/website#63]
https://api-platform.com/docs/core/getting-started

<img width="444" alt="capture d ecran 2018-07-20 a 12 22 57" src="https://user-images.githubusercontent.com/57224/42997624-ac429214-8c17-11e8-90e1-4128df77be15.png">

This link points to `https://api-platform.com/docs/core/index` instead of `https://api-platform.com/docs/core/`

**Comment by Mathieudewet** [comment]
Will also be resolve by https://github.com/api-platform/website/pull/70 (to verify).
