### ISSUE TITLE
Getting started documentation link is broken

### ISSUE THREAD

**Issue by momozor** [api-platform/website#97]
https://api-platform.com/docs/core/getting-started/#before-reading-this-documentation is where the broken link can be found. I personally believe it does affect all links to every index.md file too.

**Comment by dunglas** [comment]
@Fabious do you have an idea of what's going on?

**Comment by teohhanhui** [comment]
I think

https://github.com/api-platform/website/blob/ec087a281984425e7aef1e11c3e6ce1963564202/gatsby-node.js#L102

should be

```js
let newUrl = url.replace('.md', '/').replace(/\/index\/$/, '/');
```

**Comment by teohhanhui** [comment]
Also

https://github.com/api-platform/website/blob/ec087a281984425e7aef1e11c3e6ce1963564202/gatsby-node.js#L115

has no effect as it's not used later.

Is that intended?

**Comment by Fabious** [comment]
Yep saw this issue, Han is right about the source of the problem.

Can't fix it for the moment as i'm in recovery, but it should be easy to fix.
